### ISSUE TITLE
The latex-pdf example is missing a "txi" input file

### ISSUE THREAD

**Issue by celtic-coder** [leo-editor/snippets#2]
Hi Rob (@largo84),

Line 15 of "snippets/examples/workflow/latex-pdf/Client/SGC-H120 Reusable Content.tex"is referencing a "txi" file that is not included in the example project. The line is:

**\input{"Client\space Variables.txi"} % Sets the client name and other related client-specific commands.**

I presume that "**\theSchool**", for example, is defined in this file?

Thanks for your example Leo files! They have given me ideas on a different approach to create LaTeX files.

Kind Regards,
Liam

**Comment by largo84** [comment]
Hmm, actually no, it's somewhere else (perhaps another file I neglected to include, sorry). Glad you find it useful. Might be a bit, but will scrounge around and see if I can fix that lapse.

**Comment by largo84** [comment]
Just added the client variable file (not that you need it, except that processing the file will fail if the file isn't present).

**Comment by celtic-coder** [comment]
Adding this "txi" file has helped! Thanks!

I have a further question: In "SGC-H120 Reusable Content.tex" there is a reference to "\theSchool" at lines 105, 107, and 146. However, I do not see it being defined with a "\newcommand". Am I missing something?

**Comment by largo84** [comment]
I added the lines in an earlier commit. In the .leo file, look in the << Project Variables >> node.
