### ISSUE TITLE
New .leo file for Explore and Shell buttons is invalid somehow

### ISSUE THREAD

**Issue by tbpassin** [leo-editor/snippets#3]
Something is wrong with the new .leo file for Explore and Shell buttons.  When I try to load it, I get:
```
bad .leo file: tpassin_setting_tricks.leo
```

Ah, I see.  When I saved it I got the HTML rendering, not the actual file itself. Hmm, now to see how to do that without bothering to clone the repo.

**Comment by maphew** [comment]
Use the [raw] button when looking at the file on GitHub (https://github.com/leo-editor/snippets/blob/master/buttons/tpassin_setting_tricks.leo)

It uses `https://raw.githubusercontent.com` domain as url prefix to the files path:
https://raw.githubusercontent.com/leo-editor/snippets/master/buttons/tpassin_setting_tricks.leo

**Comment by tbpassin** [comment]
Funny, I looked for it onriginally and didn't see it, though I see it now.  Anyway, I downloaded the whole repo as a zip file, so it worked out anyway.

**Comment by maphew** [comment]
_tim-towdy_ (tmtowtdi - there's more than on way to do it) as the perl folks like to say ;-)
